In [1]:
import urllib,sys
import ssl
import json
import pandas as pd

host = 'https://jisunews.market.alicloudapi.com'
path = '/news/get'
method = 'GET'
appcode = '111dae0090ff4fd4bce69fa8dbd71132'
channels =['%E5%A4%B4%E6%9D%A1', '%E6%96%B0%E9%97%BB', '%E8%B4%A2%E7%BB%8F',
         '%E4%BD%93%E8%82%B2', '%E5%A8%B1%E4%B9%90', '%E5%86%9B%E4%BA%8B',
         '%E6%95%99%E8%82%B2', '%E7%A7%91%E6%8A%80', 'NBA',
         '%E8%82%A1%E7%A5%A8', '%E6%98%9F%E5%BA%A7','%E5%A5%B3%E6%80%A7',
         '%E5%81%A5%E5%BA%B7', '%E8%82%B2%E5%84%BF']
# 头条，新闻，财经，
# 体育，娱乐，军事，
# 教育，科技，NBA，
# 股票，星座，女性，
# 健康，育儿

j = 0
df = pd.DataFrame()
for channel in channels:    
    querys = 'channel=' + channel + '&num=40&start='

    for i in range(25):
        num = 40 * i
        bodys = {}
        url = host + path + '?' + querys + str(num)

        request = urllib.request.Request(url)
        request.add_header('Authorization', 'APPCODE ' + appcode)
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        response = urllib.request.urlopen(request, context=ctx)
        content = response.read()

        content_json = json.loads(content)

        df_temp = pd.DataFrame(content_json['result']['list'])
        df = df.append(df_temp)
#         print(i+1,'/','25')
    j += 1
    print(j,'/','14')

1 / 14
2 / 14
3 / 14
4 / 14
5 / 14
6 / 14
7 / 14
8 / 14
9 / 14
10 / 14
11 / 14
12 / 14
13 / 14
14 / 14

In [2]:
# import requests

In [3]:
# appcode = '111dae0090ff4fd4bce69fa8dbd71132'
# channel = '育儿'
# url = 'http(s)://jisunews.market.alicloudapi.com/news/get'
# payload = {'channel': channel}
# headers = {'Authorization': 'APPCODE {}'.format(appcode)}
# r = requests.get(url, params=payload, headers=headers)
# r.content

In [4]:
df.index = range(len(df))
df.to_csv('Total_data.csv')

In [91]:
from sklearn.ensemble import GradientBoostingRegressor
import pandas as pd
from sklearn.feature_selection import RFECV
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

In [63]:
df = pd.read_csv('s.csv')

In [72]:
df.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,3991,3992,3993,3994,3995,3996,3997,3998,3999,4000
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,14
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,14
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,14
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,14
4,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.051784,14

In [70]:
X = df.iloc[:,1:4001]
X.head()

,0,1,2,3,4,5,6,7,8,9,...,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.051784

In [79]:
y[y.isnull().values==True]

Empty DataFrame
Columns: [4000]
Index: []

In [73]:
y = pd.DataFrame(df.iloc[:,-1])
y.head()

   4000
0    14
1    14
2    14
3    14
4    14

In [83]:
import numpy as np

In [84]:
np.where(np.isnan(X))

(array([], dtype=int64), array([], dtype=int64))

In [98]:
def choose_feature(X,y):
    params = {'n_estimators':100, 'max_depth':4, 'min_samples_split':4, 'learning_rate':.2}
    GB = GradientBoostingClassifier(**params)
    model = GB
    rfecv = RFECV(estimator=model, step=1, cv=2, verbose=3, n_jobs=-1)
    rfecv.fit(X, y)
    var_selected = pd.DataFrame(sorted(zip(map(lambda x: round(x), rfecv.ranking_), data.columns)),
                            columns = ['ranking', 'variable'])
    pd.options.display.max_rows = 150
    return rfecv.n_features_, var_selected.variable[:rfecv.n_features_]

In [90]:
a,b = choose_feature(X,y)

/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

KeyboardInterrupt:

In [96]:
def choose_models(nstop, X_trntst, Y_trntst):
    rsq_trn = pd.DataFrame(np.zeros((nstop, 3)), columns =['NN','GB','RF'])
    rsq_tst = pd.DataFrame(np.zeros((nstop, 3)), columns =['NN','GB','RF'])
    rsq_validate = pd.DataFrame(np.zeros((1, 3)), columns =['NN','GB','RF'])
    
    for n in range(nstop):
        X_trn, X_tst, Y_trn, Y_tst = train_test_split(X_trntst, Y_trntst, test_size = .3)
        X_trn_save = X_trn.copy()
        X_tst_save = X_tst.copy()
        Y_trn_save = Y_trn.copy()
        Y_tst_save = Y_tst.copy()
 


    # Neural net   
        NN = MLPClassifier(hidden_layer_sizes=(4,),activation='tanh',solver='adam',
                          learning_rate='adaptive',max_iter=10000,learning_rate_init=.01,alpha=.01)
        NN.fit(X_trn,Y_trn)
        predict_NN_trn = NN.predict(X_trn)
        predict_NN_tst = NN.predict(X_tst)
        rsq_trn.loc[n,'NN'] = f1_score(Y_trn,predict_NN_trn, average='micro')
        rsq_tst.loc[n,'NN'] = f1_score(Y_tst,predict_NN_tst, average='micro')

        X_trn = X_trn_save
        X_tst = X_tst_save
        Y_trn = Y_trn_save
        Y_trn = Y_trn_save


    # Gradient boosting tree    
        params = {'n_estimators':300, 'max_depth':5, 'min_samples_split':20, 'learning_rate':.2}
        GB = GradientBoostingClassifier(**params)
        GB.fit(X_trn,Y_trn)
        predict_GB_trn = GB.predict(X_trn)
        predict_GB_tst = GB.predict(X_tst)
        rsq_trn.loc[n,'GB'] = f1_score(Y_trn,predict_GB_trn, average='micro')
        rsq_tst.loc[n,'GB'] = f1_score(Y_tst,predict_GB_tst, average='micro')

        X_trn = X_trn_save
        X_tst = X_tst_save
        Y_trn = Y_trn_save
        Y_tst = Y_tst_save


    # Random forest
        RF = RandomForestClassifier(n_estimators=10, max_depth=20)    
        RF.fit(X_trn,Y_trn)
        predict_RF_trn = RF.predict(X_trn)
        predict_RF_tst = RF.predict(X_tst)
        rsq_trn.loc[n,'RF'] = f1_score(Y_trn,predict_RF_trn, average='micro')
        rsq_tst.loc[n,'RF'] = f1_score(Y_tst,predict_RF_tst, average='micro')
    
    return rsq_trn,rsq_tst

In [97]:
df1,df2 = choose_models(10, X, y)

/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:1450: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/meiqiuyu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:47: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [99]:
df1

         NN        GB        RF
0  0.992340  0.996915  0.895957
1  0.992766  0.996915  0.901809
2  0.993617  0.997340  0.902128
3  0.992872  0.995638  0.891277
4  0.994362  0.996915  0.881915
5  0.993511  0.997553  0.879787
6  0.994362  0.997340  0.877447
7  0.992872  0.997447  0.896277
8  0.993617  0.996383  0.892979
9  0.993511  0.997128  0.894787

In [100]:
df2

         NN        GB        RF
0  0.865724  0.889303  0.824274
1  0.872921  0.897245  0.831720
2  0.862000  0.885331  0.828990
3  0.860511  0.895011  0.827749
4  0.872921  0.883098  0.820551
5  0.861008  0.888806  0.819558
6  0.866468  0.887069  0.825515
7  0.868702  0.889799  0.834202
8  0.867709  0.882849  0.819062
9  0.867461  0.890792  0.825019

In [101]:
df2.mean()

NN    0.866543
GB    0.888930
RF    0.825664
dtype: float64

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('s.csv')
df2 = pd.read_csv('final_data_2.csv')

In [5]:
df3 = pd.read_csv('Total_data.csv')

In [6]:
df3.category.unique()

array(['news', 'sports', 'ent', 'finance', 'tech', 'mil', 'video', 'edu',
       'baby', 'money', 'sifa', 'top', 'mobile', 'digi', nan, 'ast', 'mp',
       'lady', 'eladies', 'zx', 'ntes', 'health', 'fashion'], dtype=object)

In [6]:
df3[df3.category=='health']

,Unnamed: 0,category,content,pic,src,time,title,url,weburl
12026,12026,health,"<p class=""art_p""><span style=""font-size: 18px;...",https://n.sinaimg.cn/health/transform/59/w550h...,新浪健康,2019-10-31 14:12:00,罗氏携巨型“魔方”登陆“魔都”进博会,http://health.sina.cn/news/2019-10-31/detail-i...,http://health.sina.com.cn/news/2019-10-31/doc-...
12089,12089,health,"<p class=""art_p"">文章来源：科普中国微平台</p>\n<p class=""a...",https://n.sinaimg.cn/health/transform/739/w550...,新浪健康,2019-05-18 02:37:00,万万没想到这个习惯能防癌,http://health.sina.cn/healthcare/2018-05-18/de...,http://health.sina.com.cn/hc/2018-05-18/doc-ih...
12090,12090,health,"<p class=""art_p"">多项研究表明，久坐有害身体健康，适当运动有助于减轻这种伤害...",https://n.sinaimg.cn/health/transform/20160525...,新浪健康综合,NaN,走路速度能预测寿命,http://health.sina.cn/disease/2018-05-26/detai...,http://health.sina.com.cn/d/2018-05-26/doc-iha...
12091,12091,health,"<p class=""art_p"">“每天应喝8杯水”的观念已经深入人心。但人们往往发现，在实...",https://n.sinaimg.cn/health/transform/101/w550...,生命时报,2019-05-31 01:08:00,夏季补水不得不吃食物大排名,http://health.sina.cn/healthcare/2018-05-31/de...,http://health.sina.com.cn/hc/2018-05-31/doc-ih...
12092,12092,health,"<p class=""art_p"">专家：</p><p class=""art_p"">著名心血管...",https://n.sinaimg.cn/health/transform/20170629...,健康时报,2019-05-28 01:01:00,心脏报警10个信号 你注意到了吗,http://health.sina.cn/disease/2018-05-28/detai...,http://health.sina.com.cn/d/2018-05-28/doc-iha...
12161,12161,health,"<p class=""art_p""><span style=""font-size: 16px;...",https://n.sinaimg.cn/health/transform/116/w550...,新浪健康,2019-10-21 11:17:00,“骨舞岁月·不屈年华”唤醒骨质疏松防控意识意识,http://health.sina.cn/news/2019-10-21/detail-i...,http://health.sina.com.cn/news/2019-10-21/doc-...
12167,12167,health,"<p class=""art_p""><span>本文转自：医学界智库</span></p>\n...",https://n.sinaimg.cn/health/transform/49/w550h...,新浪健康,2019-10-21 17:39:00,一手重磅新药，一手数字转型，优时比中国的免疫新战略,http://health.sina.cn/news/2019-10-21/detail-i...,http://health.sina.com.cn/news/2019-10-21/doc-...
12180,12180,health,"<p class=""art_p""><span style=""font-size: 16px;...",https://n.sinaimg.cn/health/transform/31/w491h...,新浪健康,2019-10-21 11:33:00,武田中国与中国罕见病联盟深化协作，加强罕见病诊疗管理及保障,http://health.sina.cn/2019-10-21/detail-iicezu...,http://health.sina.com.cn/news/2019-10-21/doc-...
12208,12208,health,"<p class=""art_p""><span style=""line-height: 150...",https://n.sinaimg.cn/health/transform/18/w372h...,新浪健康,2019-10-16 16:31:00,武汉梨园街东湖社区：不忘初心，砥砺前行,http://health.sina.cn/news/2019-10-16/detail-i...,http://health.sina.com.cn/news/2019-10-16/doc-...

In [48]:
df1.iloc[96,:][df1.iloc[96,:]!=0]

Unnamed: 0    96.0
4000          20.0
Name: 96, dtype: float64

In [3]:
df2.head(20)

    Unnamed: 0                                                  0     1
0            0  古人云：赐子千金，不如教子一艺；教子一艺，不如赐子好名。因此无论起名或改名，一定要慎之又慎，...  baby
1            1  现在很多人都会把水逆当成“倒霉”的代名词，然而水逆究竟是怎么回事呢？今天我们就来简单分析一下...  news
2            2  人的一生就像花的四季“我开了……我绿了……我枯了……我秃了……”你永远也猜不到明天和“绿帽”...   mil
3            3  霜降过后，进入了深秋，今天小编就整理了一首二胡《晚秋》，以及让人非常舒服的5句话，要送给大家...   mil
4            4  一问自己活得疲惫吗？为了生活日夜奔波，省吃俭用钱也没攒几个，最后烙下个病身子，给座金山也没福...  news
5            5  萨克斯《雨夜的浪漫》秋雨，其实是一种心情。微雨霏霏，是清新是自然是感动，那凉意是一种温暖也是...  news
6            6  01生活换位思考，珍惜才配拥有这张图告诉我们：生活本来不容易，当你觉得容易的时候，肯定是有人...  ntes
7            7  （提醒：建议在WiFi环境下观看视频）1人穷时，别走亲戚，人饿时，别吃辣椒，有钱时，别总炫耀...  news
8            8  （提醒：建议在WiFi环境下观看视频）来源：新浪博客作者：孟英老同学微信群赞彼此相见已不愁距...  news
9            9  （提醒：建议在WiFi环境下观看视频）早起早睡，不做“夜猫子”；少荤多素，不做“肥肚子”；适...  news
10          10  观自ほら足元を见てごらんこれがあなたの步む道ほら前を见てごらんあれがあなたの未来母がくれたた...  news
11          11  （提醒：建议在WIFI环境下观看视频）人这一辈子，活，就要真真诚诚！堂堂正正做人，坦坦荡荡行...   mil
12          12  01大多数人的烦恼，来自于不假思索跟着大部队走。大部队说，要先有钱才能有面子，于是终日焦虑财...   mil
13          13  生活不易，大多数成年人对这四个字都深有感触。昨天，杭州萧山一小伙在工作中突然崩溃了，坐在地上...  news
14          14  但真正的生活，却没有那么简单，必定充满着柴米油盐里的鸡毛蒜皮。《恋梦空间》里，大S说过的一句...   ent
15          15  那些看似微小却高贵的善良，更让我们肃然起敬。高级的善良人生中总有那么一刻，我们不愿面对眼前的...  news
16          16  ▼俗话说“养儿防老”，等到年龄大了的时候，养老大概是所有人最为关注的事情。年轻时揣着再多的奔...  news
17          17  从曾经的全国首富，到后来的阶下囚，再到现在出狱后，干了一件大事，让全场评委的观众都惊呆！（提...   mil
18          18  文/谨宁最近，一则“女子让座未被感谢反被打”的新闻上了热搜，很多人都奇怪，为什么让座了还被打...   mil
19          19  二胡：今宵多珍重1、学会快乐没有人会为你的痛苦买单，心情是自己的，时刻提醒自己：要快乐每一天...   mil

In [8]:
df2.head(221).sample(20)

     Unnamed: 0                                                  0       1
99           99  10月13日中午11时24分，泰安市中医医院门诊楼前停车场，上演了惊险一幕，一名男子在门诊楼...    news
141         141  站着的时候，颈椎的承受力相当于一个刚出生婴儿骑在脖子上；低头的时候，相当于一个三岁的小朋友骑...  sports
58           58  秋天如期而至，同样，伴随而来的就是秋燥，不知道大家最近是否经常能感受到咽干口干，干咳不舒，易...     edu
203         203  创可贴生活中，总免不了磕磕碰碰、受点小伤，这时候创可贴就能派上用场了。可大家真的会用创可贴吗...    news
114         114  香甜粉糯的栗子正是时令，金灿灿的果实飘着香甜气味十分诱人。栗子恐怕是最不愁做法的食材，糖炒、...     edu
79           79  一张全家福，定格时代记忆，一张全家福，见证历史变迁！今晚21:15河南卫视《全家福来了》为您...    tech
127         127  全文共823字，阅读时间约3分钟。在日常生活中损伤腰椎的事情真的很多很多久站、久坐、坐姿不正...    news
60           60  近日国内首款人造肉上市引发“吃货”们的强烈讨论有人说：“太好了，现在肉价这么贵，人造的能便宜...    news
62           62  中风多发于患有心血管疾病的老年人，这一疾病有致命的危险，即使得到了及时有效的救治，中风对大脑...    news
20           20  村长汇报工作，不笑你打我！（提醒：建议在WiFi环境下观看视频）对不起，没关系小时候，老师教...   money
15           15  那些看似微小却高贵的善良，更让我们肃然起敬。高级的善良人生中总有那么一刻，我们不愿面对眼前的...    news
220         220  说到芦荟，我们的第一反应是“美容”，但其实芦荟除了美容，它还能够帮我们的血管减龄，降低“三高...    news
107         107  “牙疼不是病，疼起来要人命”，很多人认为这是玩笑话，但最近一则新闻让人们知道，牙疼还真会丧命...    news
31           31  10月19日14时31分，河北省保定市徐水区农信社南亭分社内，有一名男童被异物卡住喉咙，出现...     ent
201         201  国庆7天小长假就要到啦许多友仔友女们就想着出国旅游去东南亚国家玩耍成了不少人第一选择但是，切...    news
144         144  来源：超级小周周平板支撑看似简单的动作，其实是消耗体能的全身运动，对腹直肌、腹外斜肌、腹内斜...    news
196         196  小儿马蹄内翻足是临床常见的小儿足部畸形，其特点是足的前半部内收、内翻，跟骨内翻、跖屈、跟腱挛...     edu
21           21  01这一辈子没混好，什么歌星，舞星，影星，笑星……这个星，那个星，一概都没混上。现在只剩最后...     ent
36           36  10月29日是“世界卒中日”，扬子晚报联合苏州市中医医院党建品牌“吴医先锋行”，在苏州市姑苏...    news
8             8  （提醒：建议在WiFi环境下观看视频）来源：新浪博客作者：孟英老同学微信群赞彼此相见已不愁距...    news

In [16]:
df2.iloc[8,1]

'（提醒：建议在WiFi环境下观看视频）来源：新浪博客作者：孟英老同学微信群赞彼此相见已不愁距离，这就是网络的奇迹。如今又发挥了微信的特点，众人在群里可随时相聚。还像我们儿时的课堂，这里充满了童年的气息。有人在群里积极发言，有人在群里微笑不语。个人的喜事和趣闻，在群里将汇成欢乐的海洋。自己的苦闷和委屈，在群里能化为清澈的小溪。我们今天又走到一起，看重的不是名利和荣誉。虽然各自的路不尽相同，但都建在同一片生存的土地！人生已进入金色的秋季，最看重的是健康和友谊。啥都不说了，缘分啊！让我们加倍地珍惜。老同学，无论我们相隔多远，我一直把你们放在我的心上！对你们的祝福永远没有停止…送给群里的亲人们！百年修得同船渡，千年修得群里聚！世间的相遇皆是一种缘分，同学们群友们，让我们一起开心地在这块天地，度过美好的一生！'